### ISSUE TITLE
Feature Request to include integration with JIRA events

### ISSUE THREAD

**Issue by zleroy** [ImpactInsights/valuestream#41]
The ability to include JIRA web hook events (similar to GitLab and Jenkins) would add a lot of value to the project in my opinion:
https://developer.atlassian.com/server/jira/platform/webhooks/

Feel free to close if you do not agree.

**Comment by dm03514** [comment]
Completely agree!!! Thank you so much for creating an issue.  I can start tackling the JIRA integration this weekend.  Will post updates here!

Will prioritize JIRA and after that will focus on docs/wiki to try and make getting setup as smooth as possible.

**Comment by zleroy** [comment]
Great, thanks so much!  I am looking forward to seeing the progress.

**Comment by dm03514** [comment]
Still planning on tackling this this weekend.

Issue Events (Kanban and Scrum) and Sprint Events look straightforward. 

Tracing support between issues and active sprint is still unknown.  Issue webhook payload includes reference to the sprint but not sure how stable it is. Outstanding question on jira support:

https://community.developer.atlassian.com/t/jira-issue-webhook-customfield-10020-issue-sprint-information/33731

----

There may be other ways to get the associated sprint for an issue:
- from the API
- through some sort of tagging scheme

But at the very least will have issue & sprint event (start, end, and state changes) support for this weekend.

After event-level support next step is to look for associated valuestream traces inside of issue descriptions/comments, so they can be associated with jenkins, github, gitlab: pull requests, builds and/or deploys.

Will keep this issue up to date with progress.

**Comment by zleroy** [comment]
Thanks!

I will try this out with our Kanban workflows.  It may be possible to use the GitLab references from the Jira integration either in the webhook directly or via the Jira API.  I will need to investigate further how to best link events across them.

**Comment by dm03514** [comment]
@zleroy 

Perfect!  Sorry haven't made this explicit yet (just focusing on events right now).  I've started to add some support for adding "value stream" specific references but so far these have been adhoc (poorly documented). 

Like for github, if you have an issue like

`https://github.com/ImpactInsights/valuestream/issues/41`

You could reference that from a pull request by having the valuestream issue identifier somewhere in the branch name:

```
vstrace-github-issue-valuestream-41
```

I'm planning to build these out and actually document them :) so that all events can reference all other events through their valuestream identifiers.  

We haven't done it yet, but when completely this means that gitlab branches or issues will just need to include the jira valuestream identifier either in the branch name or in the text bodies somewhere, and valuestream should be able to link them.  
----


Please let us know how kanban flows go, would love to hear your feedback.  Thank you !
